site_name: My Blog-wath1457-test2
site_dir: "site"
site_url: https://wath1457.github.io/

theme:
  name: material
  features:
    - content.code.copy
    - pymdownx.inlinehilite

plugins:
  - blog:
      enabled: true
      draft: true
      archive: true
      authors: true
      blog_dir: .
      authors_file: "./.authors.yml"
      
markdown_extensions:
  # code block
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  # emoji
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences
