site_name: My Blog-wath1457-test2
site_dir: "site"
site_url: https://wath1457.github.io/

theme:
  name: material
  features:
    - navigation.indexes

plugins:
  - blog:
      blog_dir: blog/
      post_dir: "{blog}/posts"
      archive: true
      enabled: true
      

markdown_extensions:
  # code block
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # emoji
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Blog: 
    - blog/index.md
