authors:
  wath1457:
    name: wath1457       # Author name
    description: Hello! # Author description
    avatar: ./images/avatar.jpg       # Author avatar # Author profile slug
    url: https://github.com/wath1457         # Author website URL