name: ci
on:
  push:
    branches:
      - mkdocs
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name wath1457
          git config user.email wath1457@gmail.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: pip install "mkdocs-material[imaging]"
      - run: mkdocs build
      - run: mkdocs gh-deploy --force --remote-branch main
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}